[package]
exclude = [
    ".git",
    ".gitignore",
    ".travis.yml",
    ".tx",
    "krankerl.toml",
    "node_modules",
    "screenshots",
    "src",
    "Makefile",
    "package.json",
    "package-lock.json",
    ".eslintrc.js",
    ".babelrc.js",
]

before_cmds = [
    "composer install",
    "npm install",
    "npm run build",
]